SELECT 
    CASE 
        WHEN V.COD_PRODUTO = 30027 THEN 'CITY_SEDAN'
        WHEN V.COD_PRODUTO = 30034 THEN 'CITY_HATCH'
        WHEN V.COD_PRODUTO = 60032 THEN 'HRV'
        WHEN V.COD_PRODUTO = 20007 THEN 'CRV'
        WHEN V.COD_PRODUTO = 20078 THEN 'ACCORD'
        WHEN V.COD_PRODUTO = 20077 THEN 'CIVIC'
        WHEN V.COD_PRODUTO = 120036 THEN 'ZRV'
        WHEN V.COD_PRODUTO = 30035 THEN 'CIVIC_TYPE_R'
        WHEN V.COD_PRODUTO = 20080 THEN 'USADOS_HONDA'
        WHEN V.COD_PRODUTO = 20081 THEN 'USADOS_OUTRAS_MARCAS'
    END AS MODELO,
    CASE 
        WHEN V.COD_PRODUTO IN (20080, 20081) THEN 'USADOS'
        ELSE PM.LINHA
    END AS VERSAO,
    COUNT(*) AS TOTAL_VENDAS,
    ROUND(COUNT(*) / 365, 2) AS MEDIA_DIARIA
FROM VENDAS V 
INNER JOIN PRODUTOS_MODELOS PM ON V.COD_PRODUTO = PM.COD_PRODUTO
                              AND V.COD_MODELO = PM.COD_MODELO
WHERE V.EMISSAO >= TRUNC(ADD_MONTHS(SYSDATE, -12), 'MM') 
AND V.COD_OPERACAO IN (4,9)
GROUP BY V.COD_PRODUTO, PM.LINHA
ORDER BY V.COD_PRODUTO, PM.LINHA;
