SELECT DISTINCT
  V.CHASSI_COMPLETO CHASSI,
  CASE
      WHEN P.DESCRICAO_PRODUTO = 'CITY' THEN 'CITY SEDAN'
      WHEN P.DESCRICAO_PRODUTO = 'CITY HATCH' THEN 'CITY HATCH'
      WHEN P.DESCRICAO_PRODUTO = 'HRV' THEN 'HRV'
      WHEN P.DESCRICAO_PRODUTO IN ('CRV', 'ZR-V', 'ACCORD', 'CIVIC', 'CIVIC TYPE R') THEN 'IMPORTADOS'
      WHEN P.DESCRICAO_PRODUTO LIKE 'USADOS%' AND V.COD_PATIO IN (27,34) THEN 'REPASSE'
      WHEN P.DESCRICAO_PRODUTO LIKE 'USADOS%' AND V.COD_PATIO NOT IN (27,34) THEN 'SHOWROOM'
  END TIPO, 
  P.DESCRICAO_PRODUTO PRODUTO, 
  PM.DESCRICAO_MODELO MODELO, 
  PM.LINHA, 
  V.RESERVADO,
  V.NOVO_USADO,
  V.PRECO_TABELA VALOR,
  ROUND(SYSDATE - V.DATA_FATURAMENTO) DPT
FROM VEICULOS V
INNER JOIN PRODUTOS P ON V.COD_PRODUTO = P.COD_PRODUTO
INNER JOIN PRODUTOS_MODELOS PM ON V.COD_MODELO = PM.COD_MODELO 
                              AND P.COD_PRODUTO = PM.COD_PRODUTO
LEFT JOIN VEICULOS_PROPOSTAS VP ON V.CHASSI_RESUMIDO = VP.CHASSI_RESUMIDO
                               AND VP.STATUS_PROPOSTA NOT IN ('C', 'V')
WHERE V.STATUS = 'E';
